### PR TITLE
repro!

### PR DESCRIPTION
**Pull request by jeremypress**
hey @sabrenner. I was able to narrow down what's happening
1. A request comes in, and we call next.js's handle method
2. an exception occurs, most often a timeout
3. our errorhandler (in our case sentry) catches the error and logs it
4. we then render the error page so the user is redirected correctly

The second handle for the error page is what causes the error! if you run the server and hit /hello you should see it!

### CODE REVIEW

**Comment by sabrenner** [comment]
@jeremypress  Thanks, I was able to use this to see the issue on my side! Interestingly, though, when I set `dev` to `false`, I didn't see the issue - I'll investigate this interaction and come up with a mitigation in `dd-trace`.

**Comment by sabrenner** [comment]
@jeremypress I wanted to quickly check that, since I was only seeing this happening when enabling development mode via `dev: true`, is this error something that's happening in production for you? Or is it just when development mode is enabled?

**Comment by jeremypress** [comment]
> @jeremypress I wanted to quickly check that, since I was only seeing this happening when enabling development mode via `dev: true`, is this error something that's happening in production for you? Or is it just when development mode is enabled?

We were seeing it in both places, but we definitely felt the pain in production

**Comment by sabrenner** [comment]
> We were seeing it in both places, but we definitely felt the pain in production

Ok, I will try and write a test that mimics this without setting `dev: true` - hopefully sometime next week I should have that up on `dd-trace`. Feel free to disable the `next` integration if you haven't already (`tracer.use('next', false)`, or `DD_TRACE_DISABLED_INSTRUMENTATIONS=next`) in the meantime

**Comment by sabrenner** [comment]
@jeremypress Are you able to modify this repro to have the error pop up when `dev` is set to `false`? Taking a look at this again, it wouldn't make much sense to have `dev` set to `true` for trying to write a test based off of this repro.

**Pull request merged**
